/*
 * SPDX-FileCopyrightText: 2023-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define ESP_PANEL_DRIVERS_BUS_USE_ALL                   (1)
#define ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS    (1)

#define ESP_PANEL_DRIVERS_LCD_USE_ALL                   (1)
#define ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS    (1)

#define ESP_PANEL_DRIVERS_TOUCH_MAX_POINTS              (10)
#define ESP_PANEL_DRIVERS_TOUCH_MAX_BUTTONS             (5)
#define ESP_PANEL_DRIVERS_TOUCH_USE_ALL                 (1)
#define ESP_PANEL_DRIVERS_TOUCH_COMPILE_UNUSED_DRIVERS  (1)

#define ESP_PANEL_DRIVERS_EXPANDER_USE_ALL              (1)

#define ESP_PANEL_DRIVERS_BACKLIGHT_USE_ALL             (1)
#define ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS (1)

#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_MAJOR 1
#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_MINOR 0
#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_PATCH 0
