/*
 * SPDX-FileCopyrightText: 2023-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED       (1)

#if ESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED
#define BOARD_VIEWE_UEDX80480070E_WB_A

#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_MAJOR 1
#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_MINOR 0
#define ESP_PANEL_BOARD_SUPPORTED_FILE_VERSION_PATCH 0
#endif
